
version: 2

models:
  - name: stg_address
    description: "Address data for customer"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_customer
    description: "Customer data"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_payment_methods
    description: "Payment method data"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_products
    description: "Product data"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_order_line_items
    description: "Order line item data"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null